In [1]:
%load_ext autoreload
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
from matplotlib import pyplot as plt
from whar_datasets.adapters.pytorch_location_adapter import PyTorchLocationAdapter
from whar_datasets.adapters.numpy_location import NumpyLocationAdapter
from whar_datasets.support.getter import WHARDatasetID, get_whar_cfg
import rich

In [3]:
cfg = get_whar_cfg(WHARDatasetID.UCI_HAR)
cfg.in_memory = True

dataset = NumpyLocationAdapter(cfg)
# dataset = PyTorchLocationAdapter(cfg, override_cache=False, only_imu=True)

Creating config hash...
Checking download...
Download exists.
Checking sessions...
Sessions exist.
Validating common format...
[########################################] | 100% Completed | 1.08 sms
Common format validated.
Checking windowing...
Loading config hash...
Windowing exists.
subject_ids: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
activity_ids: [0 1 2 3 4 5]
Postprocessing...
Loading all windows from single parquet file...


Splitting windows: 100%|██████████| 9499/9499 [00:01<00:00, 7288.34it/s]


Getting normalization parameters...
Loading config hash...
Creating normalization parameters hash...
Loading normalization parameters hash...
Loading all samples from single parquet file...


Reconstructing samples: 100%|██████████| 9499/9499 [00:01<00:00, 9216.69it/s]


In [7]:
rich.print(dataset.samples.shape)
rich.print(dataset.labels.shape)

(9499, 1, 128, 9)

(9499,)

In [4]:
train_dataloader, val_dataloader, test_dataloader = dataset.get_dataloaders(16)

AttributeError: 'NumpyLocationAdapter' object has no attribute 'get_dataloaders'

In [ ]:
item = next(iter(train_dataloader))
rich.print(item[0].shape)
rich.print(item[1].shape)
rich.print(item[2].shape)
rich.print(item[3])

torch.Size([16])

torch.Size([16, 128, 9])

torch.Size([16])

[
    tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
    tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
    tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
    tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
    tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
    tensor([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
    tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
]